### ISSUE TITLE
Doesnt seem to work on the latest update

### ISSUE THREAD

**Issue by sekwah41** [blecher-at/Supreme-Risk#20]
Just downloaded FAF for the first time in a while and I am unsure if im doing something wrong but the map just has no units on it when I start it. This is both on linux and windows.

**Comment by blecher-at** [comment]
Thank you for the report. I fixed the issue and it is now avalable in the repo in the V15 folder.
Currently trying to upload it to the FA Vault as well, but I am having some issues with uploading there (https://forum.faforever.com/topic/5415/cannot-upload-new-version-of-my-map-supreme-risk) ... will close this ticket once it is resolved.

**Comment by sekwah41** [comment]
Ty :D

**Comment by blecher-at** [comment]
I uploaded it to the vault. It has a new name now "Supreme Risk Forever". LMK if you want to playtest it.

**Comment by sekwah41** [comment]
Im down to playtest it :D Il try to poke a friend and see if he wants to try it at some point too.
